### ISSUE TITLE
Fix Url link for English version on 2019 website

### ISSUE THREAD

**Issue by georgically** [PyConTH/www2020#16]
## what needs to be sorted out?
Url link for 2019 English version is linked to 2020 website instead of the English version of 2019 website. 

https://2018.th.pycon.org/

**Comment by Chomtana** [comment]
### Fixed

**Pull Request:**
https://github.com/PyConTH/www/pull/228

**Preview:**
https://5e13577c859d690008603cfc--serene-mestorf-5c91d0.netlify.com/

**Comment by jean** [comment]
Fixed for current site in https://github.com/PyConTH/www2020/pull/17/commits/875fb3a1f0477b782d2cecb6f5b5ef3940c6456c
I merged #228 although sites for previous years shouldn't be getting updates any more.
