### ISSUE TITLE
Create Social Media Meta Tags for Facebook, IG and Twitter

### ISSUE THREAD

**Issue by georgically** [PyConTH/www2020#20]
# Social Media Meta Tags
### The MarCom team has found out that the meta-tags were not properly set. 

**Below are the screenshots example:**

![pycon metatags 2](https://user-images.githubusercontent.com/40323509/73329452-565ed200-4290-11ea-99bf-a2033d6473fc.jpg)

## What needs to be done?
 - set meta-tags for Facebook (Open graph), Instagram(own by FB so the same) and Twitter (has its own)
- How- to for FB using open graph: https://developers.facebook.com/docs/sharing/webmasters/
- Another reference: https://css-tricks.com/essential-meta-tags-social-media/

**Comment by jean** [comment]
@georgically who knows how to do this?

**Comment by bluenex** [comment]
According to @georgically 's description, we will need to add `<meta property="og:*" content="...">` into `<head>` of the page being shared. I did a rough inspection and found that we have 3 `<head>`s at:

- `signup.html` in `content/pages`
  - doesn't have any `meta` tag in head here
- `base.html` in `theme/templates`
- `index.html` in `theme/templates`

For `base.html` and `index.html`, they do have Twitter's meta tags which load the username from `_includes/_defaults.html`. I think we can add more social info to the `_defaults.html` and load it to the template. I can help with that.

I will also check whether the data in `defaults.html` can be loaded into the `content/pages/signup.html` or not.

**Comment by jean** [comment]
Done in #21
